# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'daqcontrol/daq_control.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(800, 670)
        mainWindow.setMinimumSize(QtCore.QSize(800, 670))
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(782, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_12 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(80, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(80, 27))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.pos_channel = QtGui.QComboBox(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_channel.sizePolicy().hasHeightForWidth())
        self.pos_channel.setSizePolicy(sizePolicy)
        self.pos_channel.setMinimumSize(QtCore.QSize(100, 27))
        self.pos_channel.setObjectName(_fromUtf8("pos_channel"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.pos_channel)
        self.label_14 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(80, 27))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.neg_channel = QtGui.QComboBox(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neg_channel.sizePolicy().hasHeightForWidth())
        self.neg_channel.setSizePolicy(sizePolicy)
        self.neg_channel.setMinimumSize(QtCore.QSize(100, 27))
        self.neg_channel.setObjectName(_fromUtf8("neg_channel"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.neg_channel)
        self.label_15 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(80, 27))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_15)
        self.range = QtGui.QComboBox(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.range.sizePolicy().hasHeightForWidth())
        self.range.setSizePolicy(sizePolicy)
        self.range.setMinimumSize(QtCore.QSize(100, 27))
        self.range.setObjectName(_fromUtf8("range"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.range)
        self.label_16 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(80, 27))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_16)
        self.Bplay = QtGui.QPushButton(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bplay.sizePolicy().hasHeightForWidth())
        self.Bplay.setSizePolicy(sizePolicy)
        self.Bplay.setMinimumSize(QtCore.QSize(100, 27))
        self.Bplay.setCheckable(True)
        self.Bplay.setObjectName(_fromUtf8("Bplay"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.Bplay)
        self.Bstop = QtGui.QPushButton(self.tab1)
        self.Bstop.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop.sizePolicy().hasHeightForWidth())
        self.Bstop.setSizePolicy(sizePolicy)
        self.Bstop.setMinimumSize(QtCore.QSize(100, 27))
        self.Bstop.setObjectName(_fromUtf8("Bstop"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.FieldRole, self.Bstop)
        self.last_value = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last_value.sizePolicy().hasHeightForWidth())
        self.last_value.setSizePolicy(sizePolicy)
        self.last_value.setMinimumSize(QtCore.QSize(100, 27))
        self.last_value.setAlignment(QtCore.Qt.AlignCenter)
        self.last_value.setObjectName(_fromUtf8("last_value"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.FieldRole, self.last_value)
        self.label_18 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(80, 27))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtGui.QLabel(self.tab1)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_20)
        self.dac_value = QtGui.QDoubleSpinBox(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dac_value.sizePolicy().hasHeightForWidth())
        self.dac_value.setSizePolicy(sizePolicy)
        self.dac_value.setMinimumSize(QtCore.QSize(100, 27))
        self.dac_value.setDecimals(3)
        self.dac_value.setSingleStep(0.1)
        self.dac_value.setObjectName(_fromUtf8("dac_value"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.FieldRole, self.dac_value)
        self.sb_period = QtGui.QDoubleSpinBox(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_period.sizePolicy().hasHeightForWidth())
        self.sb_period.setSizePolicy(sizePolicy)
        self.sb_period.setMinimumSize(QtCore.QSize(100, 27))
        self.sb_period.setMinimum(0.1)
        self.sb_period.setMaximum(99.9)
        self.sb_period.setSingleStep(0.1)
        self.sb_period.setProperty("value", 1.0)
        self.sb_period.setObjectName(_fromUtf8("sb_period"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.sb_period)
        self.Bset_voltage = QtGui.QPushButton(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bset_voltage.sizePolicy().hasHeightForWidth())
        self.Bset_voltage.setSizePolicy(sizePolicy)
        self.Bset_voltage.setMinimumSize(QtCore.QSize(100, 27))
        self.Bset_voltage.setObjectName(_fromUtf8("Bset_voltage"))
        self.formLayout_5.setWidget(10, QtGui.QFormLayout.FieldRole, self.Bset_voltage)
        self.horizontalLayout.addLayout(self.formLayout_5)
        self.plotWidget = MPL_Widget(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(520, 532))
        self.plotWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.horizontalLayout.addWidget(self.plotWidget)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(15, 10, 171, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, 271, 452))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.cbD1 = QtGui.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbD1.sizePolicy().hasHeightForWidth())
        self.cbD1.setSizePolicy(sizePolicy)
        self.cbD1.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD1.setObjectName(_fromUtf8("cbD1"))
        self.cbD1.addItem(_fromUtf8(""))
        self.cbD1.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbD1, 0, 1, 1, 1)
        self.cbD5 = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbD5.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD5.setObjectName(_fromUtf8("cbD5"))
        self.cbD5.addItem(_fromUtf8(""))
        self.cbD5.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbD5, 4, 1, 1, 1)
        self.cbD2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbD2.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD2.setObjectName(_fromUtf8("cbD2"))
        self.cbD2.addItem(_fromUtf8(""))
        self.cbD2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbD2, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.cbD3 = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbD3.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD3.setObjectName(_fromUtf8("cbD3"))
        self.cbD3.addItem(_fromUtf8(""))
        self.cbD3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbD3, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.Digital4 = QtGui.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital4.sizePolicy().hasHeightForWidth())
        self.Digital4.setSizePolicy(sizePolicy)
        self.Digital4.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital4.setObjectName(_fromUtf8("Digital4"))
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName(_fromUtf8("page_11"))
        self.DDI4 = QtGui.QLCDNumber(self.page_11)
        self.DDI4.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI4.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
""))
        self.DDI4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DDI4.setFrameShadow(QtGui.QFrame.Raised)
        self.DDI4.setLineWidth(1)
        self.DDI4.setNumDigits(1)
        self.DDI4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.DDI4.setProperty("value", 1.0)
        self.DDI4.setObjectName(_fromUtf8("DDI4"))
        self.Digital4.addWidget(self.page_11)
        self.page_12 = QtGui.QWidget()
        self.page_12.setObjectName(_fromUtf8("page_12"))
        self.SDO4 = QtGui.QSlider(self.page_12)
        self.SDO4.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO4.setStyleSheet(_fromUtf8("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
""))
        self.SDO4.setMaximum(1)
        self.SDO4.setTracking(True)
        self.SDO4.setOrientation(QtCore.Qt.Horizontal)
        self.SDO4.setInvertedAppearance(False)
        self.SDO4.setInvertedControls(False)
        self.SDO4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SDO4.setTickInterval(1)
        self.SDO4.setObjectName(_fromUtf8("SDO4"))
        self.label_28 = QtGui.QLabel(self.page_12)
        self.label_28.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.Digital4.addWidget(self.page_12)
        self.gridLayout.addWidget(self.Digital4, 3, 2, 1, 1)
        self.cbD4 = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbD4.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD4.setObjectName(_fromUtf8("cbD4"))
        self.cbD4.addItem(_fromUtf8(""))
        self.cbD4.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbD4, 3, 1, 1, 1)
        self.Digital5 = QtGui.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital5.sizePolicy().hasHeightForWidth())
        self.Digital5.setSizePolicy(sizePolicy)
        self.Digital5.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital5.setObjectName(_fromUtf8("Digital5"))
        self.page_13 = QtGui.QWidget()
        self.page_13.setObjectName(_fromUtf8("page_13"))
        self.DDI5 = QtGui.QLCDNumber(self.page_13)
        self.DDI5.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI5.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
""))
        self.DDI5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DDI5.setFrameShadow(QtGui.QFrame.Raised)
        self.DDI5.setLineWidth(1)
        self.DDI5.setNumDigits(1)
        self.DDI5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.DDI5.setProperty("value", 1.0)
        self.DDI5.setObjectName(_fromUtf8("DDI5"))
        self.Digital5.addWidget(self.page_13)
        self.page_14 = QtGui.QWidget()
        self.page_14.setObjectName(_fromUtf8("page_14"))
        self.SDO5 = QtGui.QSlider(self.page_14)
        self.SDO5.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO5.setStyleSheet(_fromUtf8("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
""))
        self.SDO5.setMaximum(1)
        self.SDO5.setTracking(True)
        self.SDO5.setOrientation(QtCore.Qt.Horizontal)
        self.SDO5.setInvertedAppearance(False)
        self.SDO5.setInvertedControls(False)
        self.SDO5.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SDO5.setTickInterval(1)
        self.SDO5.setObjectName(_fromUtf8("SDO5"))
        self.label_29 = QtGui.QLabel(self.page_14)
        self.label_29.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.Digital5.addWidget(self.page_14)
        self.gridLayout.addWidget(self.Digital5, 4, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 5, 0, 1, 1)
        self.cbD6 = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbD6.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD6.setObjectName(_fromUtf8("cbD6"))
        self.cbD6.addItem(_fromUtf8(""))
        self.cbD6.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbD6, 5, 1, 1, 1)
        self.Digital2 = QtGui.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital2.sizePolicy().hasHeightForWidth())
        self.Digital2.setSizePolicy(sizePolicy)
        self.Digital2.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital2.setObjectName(_fromUtf8("Digital2"))
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.DDI2 = QtGui.QLCDNumber(self.page_7)
        self.DDI2.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI2.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
""))
        self.DDI2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DDI2.setFrameShadow(QtGui.QFrame.Raised)
        self.DDI2.setLineWidth(1)
        self.DDI2.setNumDigits(1)
        self.DDI2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.DDI2.setProperty("value", 1.0)
        self.DDI2.setObjectName(_fromUtf8("DDI2"))
        self.Digital2.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.SDO2 = QtGui.QSlider(self.page_8)
        self.SDO2.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO2.setStyleSheet(_fromUtf8("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
""))
        self.SDO2.setMaximum(1)
        self.SDO2.setTracking(True)
        self.SDO2.setOrientation(QtCore.Qt.Horizontal)
        self.SDO2.setInvertedAppearance(False)
        self.SDO2.setInvertedControls(False)
        self.SDO2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SDO2.setTickInterval(1)
        self.SDO2.setObjectName(_fromUtf8("SDO2"))
        self.label_21 = QtGui.QLabel(self.page_8)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.Digital2.addWidget(self.page_8)
        self.gridLayout.addWidget(self.Digital2, 1, 2, 1, 1)
        self.Digital3 = QtGui.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital3.sizePolicy().hasHeightForWidth())
        self.Digital3.setSizePolicy(sizePolicy)
        self.Digital3.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital3.setObjectName(_fromUtf8("Digital3"))
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.DDI3 = QtGui.QLCDNumber(self.page_9)
        self.DDI3.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI3.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
""))
        self.DDI3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DDI3.setFrameShadow(QtGui.QFrame.Raised)
        self.DDI3.setLineWidth(1)
        self.DDI3.setNumDigits(1)
        self.DDI3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.DDI3.setProperty("value", 1.0)
        self.DDI3.setObjectName(_fromUtf8("DDI3"))
        self.Digital3.addWidget(self.page_9)
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.SDO3 = QtGui.QSlider(self.page_10)
        self.SDO3.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO3.setStyleSheet(_fromUtf8("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
""))
        self.SDO3.setMaximum(1)
        self.SDO3.setTracking(True)
        self.SDO3.setOrientation(QtCore.Qt.Horizontal)
        self.SDO3.setInvertedAppearance(False)
        self.SDO3.setInvertedControls(False)
        self.SDO3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SDO3.setTickInterval(1)
        self.SDO3.setObjectName(_fromUtf8("SDO3"))
        self.label_22 = QtGui.QLabel(self.page_10)
        self.label_22.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.Digital3.addWidget(self.page_10)
        self.gridLayout.addWidget(self.Digital3, 2, 2, 1, 1)
        self.Digital6 = QtGui.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital6.sizePolicy().hasHeightForWidth())
        self.Digital6.setSizePolicy(sizePolicy)
        self.Digital6.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital6.setObjectName(_fromUtf8("Digital6"))
        self.page_15 = QtGui.QWidget()
        self.page_15.setObjectName(_fromUtf8("page_15"))
        self.DDI6 = QtGui.QLCDNumber(self.page_15)
        self.DDI6.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI6.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
""))
        self.DDI6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DDI6.setFrameShadow(QtGui.QFrame.Raised)
        self.DDI6.setLineWidth(1)
        self.DDI6.setNumDigits(1)
        self.DDI6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.DDI6.setProperty("value", 1.0)
        self.DDI6.setObjectName(_fromUtf8("DDI6"))
        self.Digital6.addWidget(self.page_15)
        self.page_16 = QtGui.QWidget()
        self.page_16.setObjectName(_fromUtf8("page_16"))
        self.SDO6 = QtGui.QSlider(self.page_16)
        self.SDO6.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO6.setStyleSheet(_fromUtf8("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
""))
        self.SDO6.setMaximum(1)
        self.SDO6.setTracking(True)
        self.SDO6.setOrientation(QtCore.Qt.Horizontal)
        self.SDO6.setInvertedAppearance(False)
        self.SDO6.setInvertedControls(False)
        self.SDO6.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SDO6.setTickInterval(1)
        self.SDO6.setObjectName(_fromUtf8("SDO6"))
        self.label_30 = QtGui.QLabel(self.page_16)
        self.label_30.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.Digital6.addWidget(self.page_16)
        self.gridLayout.addWidget(self.Digital6, 5, 2, 1, 1)
        self.Digital1 = QtGui.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital1.sizePolicy().hasHeightForWidth())
        self.Digital1.setSizePolicy(sizePolicy)
        self.Digital1.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital1.setObjectName(_fromUtf8("Digital1"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.DDI1 = QtGui.QLCDNumber(self.page_5)
        self.DDI1.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DDI1.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
""))
        self.DDI1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DDI1.setFrameShadow(QtGui.QFrame.Raised)
        self.DDI1.setLineWidth(1)
        self.DDI1.setNumDigits(1)
        self.DDI1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.DDI1.setProperty("value", 1.0)
        self.DDI1.setObjectName(_fromUtf8("DDI1"))
        self.Digital1.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.label_17 = QtGui.QLabel(self.page_6)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(_fromUtf8(""))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.SDO1 = QtGui.QSlider(self.page_6)
        self.SDO1.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO1.setStyleSheet(_fromUtf8("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
""))
        self.SDO1.setMaximum(1)
        self.SDO1.setTracking(True)
        self.SDO1.setOrientation(QtCore.Qt.Horizontal)
        self.SDO1.setInvertedAppearance(False)
        self.SDO1.setInvertedControls(False)
        self.SDO1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SDO1.setTickInterval(1)
        self.SDO1.setObjectName(_fromUtf8("SDO1"))
        self.Digital1.addWidget(self.page_6)
        self.gridLayout.addWidget(self.Digital1, 0, 2, 1, 1)
        self.Bupdate = QtGui.QPushButton(self.tab_2)
        self.Bupdate.setGeometry(QtCore.QRect(250, 500, 99, 27))
        self.Bupdate.setObjectName(_fromUtf8("Bupdate"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.sW = QtGui.QStackedWidget(self.tab)
        self.sW.setGeometry(QtCore.QRect(0, 50, 280, 200))
        self.sW.setMinimumSize(QtCore.QSize(280, 200))
        self.sW.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sW.setAutoFillBackground(False)
        self.sW.setObjectName(_fromUtf8("sW"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_25 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_25)
        self.label_3 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.Bstart_encoder = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstart_encoder.sizePolicy().hasHeightForWidth())
        self.Bstart_encoder.setSizePolicy(sizePolicy)
        self.Bstart_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstart_encoder.setStyleSheet(_fromUtf8(""))
        self.Bstart_encoder.setCheckable(True)
        self.Bstart_encoder.setObjectName(_fromUtf8("Bstart_encoder"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.Bstart_encoder)
        self.Bstop_encoder = QtGui.QPushButton(self.page)
        self.Bstop_encoder.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop_encoder.sizePolicy().hasHeightForWidth())
        self.Bstop_encoder.setSizePolicy(sizePolicy)
        self.Bstop_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstop_encoder.setObjectName(_fromUtf8("Bstop_encoder"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.Bstop_encoder)
        self.mode_encoder = QtGui.QComboBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_encoder.sizePolicy().hasHeightForWidth())
        self.mode_encoder.setSizePolicy(sizePolicy)
        self.mode_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.mode_encoder.setObjectName(_fromUtf8("mode_encoder"))
        self.mode_encoder.addItem(_fromUtf8(""))
        self.mode_encoder.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.mode_encoder)
        self.result_encoder = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_encoder.sizePolicy().hasHeightForWidth())
        self.result_encoder.setSizePolicy(sizePolicy)
        self.result_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.result_encoder.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);"))
        self.result_encoder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.result_encoder.setFrameShadow(QtGui.QFrame.Sunken)
        self.result_encoder.setText(_fromUtf8(""))
        self.result_encoder.setObjectName(_fromUtf8("result_encoder"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.result_encoder)
        self.resolution_encoder = QtGui.QSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolution_encoder.sizePolicy().hasHeightForWidth())
        self.resolution_encoder.setSizePolicy(sizePolicy)
        self.resolution_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.resolution_encoder.setMaximum(65535)
        self.resolution_encoder.setSingleStep(1)
        self.resolution_encoder.setObjectName(_fromUtf8("resolution_encoder"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.resolution_encoder)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.sW.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_26 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_26)
        self.lEPeriod = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lEPeriod.sizePolicy().hasHeightForWidth())
        self.lEPeriod.setSizePolicy(sizePolicy)
        self.lEPeriod.setMinimumSize(QtCore.QSize(120, 27))
        self.lEPeriod.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lEPeriod.setText(_fromUtf8(""))
        self.lEPeriod.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lEPeriod.setObjectName(_fromUtf8("lEPeriod"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lEPeriod)
        self.label_2 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cbTime = QtGui.QComboBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTime.sizePolicy().hasHeightForWidth())
        self.cbTime.setSizePolicy(sizePolicy)
        self.cbTime.setMinimumSize(QtCore.QSize(120, 27))
        self.cbTime.setObjectName(_fromUtf8("cbTime"))
        self.cbTime.addItem(_fromUtf8(""))
        self.cbTime.addItem(_fromUtf8(""))
        self.cbTime.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbTime)
        self.Bstart_capture = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstart_capture.sizePolicy().hasHeightForWidth())
        self.Bstart_capture.setSizePolicy(sizePolicy)
        self.Bstart_capture.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstart_capture.setCheckable(True)
        self.Bstart_capture.setAutoRepeat(False)
        self.Bstart_capture.setAutoExclusive(False)
        self.Bstart_capture.setAutoDefault(False)
        self.Bstart_capture.setObjectName(_fromUtf8("Bstart_capture"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.Bstart_capture)
        self.Bstop_capture = QtGui.QPushButton(self.page_2)
        self.Bstop_capture.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop_capture.sizePolicy().hasHeightForWidth())
        self.Bstop_capture.setSizePolicy(sizePolicy)
        self.Bstop_capture.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstop_capture.setCheckable(False)
        self.Bstop_capture.setObjectName(_fromUtf8("Bstop_capture"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.Bstop_capture)
        self.label_31 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_31)
        self.reference_period = QtGui.QSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reference_period.sizePolicy().hasHeightForWidth())
        self.reference_period.setSizePolicy(sizePolicy)
        self.reference_period.setMinimumSize(QtCore.QSize(120, 27))
        self.reference_period.setMaximum(1000000000)
        self.reference_period.setSingleStep(100)
        self.reference_period.setProperty("value", 2000)
        self.reference_period.setObjectName(_fromUtf8("reference_period"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.reference_period)
        self.horizontalLayout_2.addLayout(self.formLayout_4)
        self.sW.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.page_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_27 = QtGui.QLabel(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_27)
        self.Bstart_counter = QtGui.QPushButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstart_counter.sizePolicy().hasHeightForWidth())
        self.Bstart_counter.setSizePolicy(sizePolicy)
        self.Bstart_counter.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstart_counter.setCheckable(True)
        self.Bstart_counter.setObjectName(_fromUtf8("Bstart_counter"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.Bstart_counter)
        self.Bstop_counter = QtGui.QPushButton(self.page_3)
        self.Bstop_counter.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop_counter.sizePolicy().hasHeightForWidth())
        self.Bstop_counter.setSizePolicy(sizePolicy)
        self.Bstop_counter.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstop_counter.setObjectName(_fromUtf8("Bstop_counter"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.Bstop_counter)
        self.counter_result = QtGui.QLabel(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counter_result.sizePolicy().hasHeightForWidth())
        self.counter_result.setSizePolicy(sizePolicy)
        self.counter_result.setMinimumSize(QtCore.QSize(120, 27))
        self.counter_result.setFrameShape(QtGui.QFrame.StyledPanel)
        self.counter_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.counter_result.setText(_fromUtf8(""))
        self.counter_result.setObjectName(_fromUtf8("counter_result"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.counter_result)
        self.horizontalLayout_4.addLayout(self.formLayout_2)
        self.sW.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.page_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 27))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.periodPWM = QtGui.QSpinBox(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodPWM.sizePolicy().hasHeightForWidth())
        self.periodPWM.setSizePolicy(sizePolicy)
        self.periodPWM.setMinimumSize(QtCore.QSize(120, 27))
        self.periodPWM.setMaximum(65535)
        self.periodPWM.setObjectName(_fromUtf8("periodPWM"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.periodPWM)
        self.label_6 = QtGui.QLabel(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.dutyPWM = QtGui.QSpinBox(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dutyPWM.sizePolicy().hasHeightForWidth())
        self.dutyPWM.setSizePolicy(sizePolicy)
        self.dutyPWM.setMinimumSize(QtCore.QSize(120, 27))
        self.dutyPWM.setMaximum(100)
        self.dutyPWM.setObjectName(_fromUtf8("dutyPWM"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dutyPWM)
        self.Bset_pwm = QtGui.QPushButton(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bset_pwm.sizePolicy().hasHeightForWidth())
        self.Bset_pwm.setSizePolicy(sizePolicy)
        self.Bset_pwm.setMinimumSize(QtCore.QSize(120, 27))
        self.Bset_pwm.setCheckable(True)
        self.Bset_pwm.setObjectName(_fromUtf8("Bset_pwm"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.Bset_pwm)
        self.Bstop_pwm = QtGui.QPushButton(self.page_4)
        self.Bstop_pwm.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop_pwm.sizePolicy().hasHeightForWidth())
        self.Bstop_pwm.setSizePolicy(sizePolicy)
        self.Bstop_pwm.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstop_pwm.setObjectName(_fromUtf8("Bstop_pwm"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.Bstop_pwm)
        self.Breset_pwm = QtGui.QPushButton(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Breset_pwm.sizePolicy().hasHeightForWidth())
        self.Breset_pwm.setSizePolicy(sizePolicy)
        self.Breset_pwm.setMinimumSize(QtCore.QSize(120, 27))
        self.Breset_pwm.setObjectName(_fromUtf8("Breset_pwm"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.Breset_pwm)
        self.horizontalLayout_5.addLayout(self.formLayout)
        self.sW.addWidget(self.page_4)
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 281, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_6 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cb = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb.sizePolicy().hasHeightForWidth())
        self.cb.setSizePolicy(sizePolicy)
        self.cb.setMinimumSize(QtCore.QSize(120, 27))
        self.cb.setObjectName(_fromUtf8("cb"))
        self.cb.addItem(_fromUtf8(""))
        self.cb.addItem(_fromUtf8(""))
        self.cb.addItem(_fromUtf8(""))
        self.cb.addItem(_fromUtf8(""))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(mainWindow)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 27))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        mainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(mainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConfig = QtGui.QAction(mainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.actionConfig.setIcon(icon)
        self.actionConfig.setIconVisibleInMenu(True)
        self.actionConfig.setObjectName(_fromUtf8("actionConfig"))
        self.toolBar.addAction(self.actionConfig)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Digital4.setCurrentIndex(0)
        self.Digital5.setCurrentIndex(0)
        self.Digital2.setCurrentIndex(0)
        self.Digital3.setCurrentIndex(0)
        self.Digital6.setCurrentIndex(0)
        self.Digital1.setCurrentIndex(0)
        self.sW.setCurrentIndex(0)
        QtCore.QObject.connect(self.Bstart_capture, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop_capture.setEnabled)
        QtCore.QObject.connect(self.Bstop_capture, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop_capture.setEnabled)
        QtCore.QObject.connect(self.Bstop_capture, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstart_capture.toggle)
        QtCore.QObject.connect(self.Bstart_counter, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop_counter.setEnabled)
        QtCore.QObject.connect(self.Bset_pwm, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop_pwm.setEnabled)
        QtCore.QObject.connect(self.Bstop_pwm, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bset_pwm.setChecked)
        QtCore.QObject.connect(self.Bstop_pwm, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop_pwm.setEnabled)
        QtCore.QObject.connect(self.Bset_pwm, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Bset_pwm.setDisabled)
        QtCore.QObject.connect(self.Bstop_pwm, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Breset_pwm.setEnabled)
        QtCore.QObject.connect(self.Bset_pwm, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Breset_pwm.setEnabled)
        QtCore.QObject.connect(self.Bstart_encoder, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop_encoder.setEnabled)
        QtCore.QObject.connect(self.Bstop_encoder, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstart_encoder.setChecked)
        QtCore.QObject.connect(self.Bstart_encoder, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Bstart_encoder.setDisabled)
        QtCore.QObject.connect(self.Bstop_encoder, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop_encoder.setEnabled)
        QtCore.QObject.connect(self.cbD2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.Digital2.setCurrentIndex)
        QtCore.QObject.connect(self.cbD3, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.Digital3.setCurrentIndex)
        QtCore.QObject.connect(self.cbD4, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.Digital4.setCurrentIndex)
        QtCore.QObject.connect(self.cbD5, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.Digital5.setCurrentIndex)
        QtCore.QObject.connect(self.cbD6, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.Digital6.setCurrentIndex)
        QtCore.QObject.connect(self.cb, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.sW.setCurrentIndex)
        QtCore.QObject.connect(self.Bstop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bplay.toggle)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop.setEnabled)
        QtCore.QObject.connect(self.Bstop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop.setEnabled)
        QtCore.QObject.connect(self.SDO1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_17.setNum)
        QtCore.QObject.connect(self.cbD1, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.Digital1.setCurrentIndex)
        QtCore.QObject.connect(self.SDO2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_21.setNum)
        QtCore.QObject.connect(self.SDO3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_22.setNum)
        QtCore.QObject.connect(self.SDO4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_28.setNum)
        QtCore.QObject.connect(self.SDO5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_29.setNum)
        QtCore.QObject.connect(self.SDO6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_30.setNum)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pos_channel.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.neg_channel.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.range.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sb_period.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "DAQControl", None))
        self.label_12.setText(_translate("mainWindow", "Analog Input", None))
        self.label_13.setText(_translate("mainWindow", "Ch +", None))
        self.label_14.setText(_translate("mainWindow", "Ch -", None))
        self.label_15.setText(_translate("mainWindow", "Range", None))
        self.label_16.setText(_translate("mainWindow", "Period (s)", None))
        self.Bplay.setText(_translate("mainWindow", "Play", None))
        self.Bstop.setText(_translate("mainWindow", "Stop", None))
        self.last_value.setText(_translate("mainWindow", "-", None))
        self.label_18.setText(_translate("mainWindow", "Last Value (V)", None))
        self.label_19.setText(_translate("mainWindow", "Analog Output", None))
        self.label_20.setText(_translate("mainWindow", "DAC Value (V)", None))
        self.Bset_voltage.setText(_translate("mainWindow", "Set Voltage", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("mainWindow", "Analog I / O", None))
        self.label_7.setText(_translate("mainWindow", "Select Input or Output", None))
        self.label_8.setText(_translate("mainWindow", "D1", None))
        self.label_23.setText(_translate("mainWindow", "D5", None))
        self.label_9.setText(_translate("mainWindow", "D2", None))
        self.cbD1.setItemText(0, _translate("mainWindow", "Input", None))
        self.cbD1.setItemText(1, _translate("mainWindow", "Output", None))
        self.cbD5.setItemText(0, _translate("mainWindow", "Input", None))
        self.cbD5.setItemText(1, _translate("mainWindow", "Output", None))
        self.cbD2.setItemText(0, _translate("mainWindow", "Input", None))
        self.cbD2.setItemText(1, _translate("mainWindow", "Output", None))
        self.label_10.setText(_translate("mainWindow", "D3", None))
        self.cbD3.setItemText(0, _translate("mainWindow", "Input", None))
        self.cbD3.setItemText(1, _translate("mainWindow", "Output", None))
        self.label_11.setText(_translate("mainWindow", "D4", None))
        self.label_28.setText(_translate("mainWindow", "0", None))
        self.cbD4.setItemText(0, _translate("mainWindow", "Input", None))
        self.cbD4.setItemText(1, _translate("mainWindow", "Output", None))
        self.label_29.setText(_translate("mainWindow", "0", None))
        self.label_24.setText(_translate("mainWindow", "D6", None))
        self.cbD6.setItemText(0, _translate("mainWindow", "Input", None))
        self.cbD6.setItemText(1, _translate("mainWindow", "Output", None))
        self.label_21.setText(_translate("mainWindow", "0", None))
        self.label_22.setText(_translate("mainWindow", "0", None))
        self.label_30.setText(_translate("mainWindow", "0", None))
        self.label_17.setText(_translate("mainWindow", "0", None))
        self.Bupdate.setText(_translate("mainWindow", "Update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Digital I / O", None))
        self.label_25.setText(_translate("mainWindow", "Result:", None))
        self.label_3.setText(_translate("mainWindow", "Select Mode:", None))
        self.label_4.setText(_translate("mainWindow", "Resolution :", None))
        self.Bstart_encoder.setText(_translate("mainWindow", "Start Encoder", None))
        self.Bstop_encoder.setText(_translate("mainWindow", "Stop Encoder", None))
        self.mode_encoder.setItemText(0, _translate("mainWindow", "Circular", None))
        self.mode_encoder.setItemText(1, _translate("mainWindow", "Lineal", None))
        self.label_26.setText(_translate("mainWindow", "Result (µs): ", None))
        self.label_2.setText(_translate("mainWindow", "Select width : ", None))
        self.cbTime.setItemText(0, _translate("mainWindow", "Low time", None))
        self.cbTime.setItemText(1, _translate("mainWindow", "High time", None))
        self.cbTime.setItemText(2, _translate("mainWindow", "Full period", None))
        self.Bstart_capture.setText(_translate("mainWindow", "Start Capture", None))
        self.Bstop_capture.setText(_translate("mainWindow", "Stop Capture", None))
        self.label_31.setText(_translate("mainWindow", "Reference: ", None))
        self.label_27.setText(_translate("mainWindow", "Result:", None))
        self.Bstart_counter.setText(_translate("mainWindow", "Start Counter", None))
        self.Bstop_counter.setText(_translate("mainWindow", "Stop Counter", None))
        self.label_5.setText(_translate("mainWindow", "Period (µs) :", None))
        self.label_6.setText(_translate("mainWindow", "Duty (%) :", None))
        self.Bset_pwm.setText(_translate("mainWindow", "Set PWM", None))
        self.Bstop_pwm.setText(_translate("mainWindow", "Stop PWM", None))
        self.Breset_pwm.setText(_translate("mainWindow", "Reset PWM", None))
        self.label.setText(_translate("mainWindow", "Select Mode:", None))
        self.cb.setItemText(0, _translate("mainWindow", "Encoder", None))
        self.cb.setItemText(1, _translate("mainWindow", "Capture", None))
        self.cb.setItemText(2, _translate("mainWindow", "Couter", None))
        self.cb.setItemText(3, _translate("mainWindow", "PWM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Timer-Counter", None))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar", None))
        self.actionConfig.setText(_translate("mainWindow", "config", None))

from widgets import MPL_Widget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

