# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'daqcontrol/daq_control.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from .widgets import MPL_Widget
from . import res_rc

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(834, 696)
        mainWindow.setMinimumSize(QtCore.QSize(800, 670))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(782, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_12 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(80, 27))
        self.label_12.setMaximumSize(QtCore.QSize(110, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(80, 27))
        self.label_13.setMaximumSize(QtCore.QSize(80, 27))
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.pos_channel = QtWidgets.QComboBox(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_channel.sizePolicy().hasHeightForWidth())
        self.pos_channel.setSizePolicy(sizePolicy)
        self.pos_channel.setMinimumSize(QtCore.QSize(100, 27))
        self.pos_channel.setMaximumSize(QtCore.QSize(100, 27))
        self.pos_channel.setObjectName("pos_channel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pos_channel)
        self.label_14 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(80, 27))
        self.label_14.setMaximumSize(QtCore.QSize(80, 27))
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.neg_channel = QtWidgets.QComboBox(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neg_channel.sizePolicy().hasHeightForWidth())
        self.neg_channel.setSizePolicy(sizePolicy)
        self.neg_channel.setMinimumSize(QtCore.QSize(100, 27))
        self.neg_channel.setMaximumSize(QtCore.QSize(100, 27))
        self.neg_channel.setObjectName("neg_channel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.neg_channel)
        self.label_15 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(80, 27))
        self.label_15.setMaximumSize(QtCore.QSize(80, 27))
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.range = QtWidgets.QComboBox(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.range.sizePolicy().hasHeightForWidth())
        self.range.setSizePolicy(sizePolicy)
        self.range.setMinimumSize(QtCore.QSize(100, 27))
        self.range.setMaximumSize(QtCore.QSize(100, 27))
        self.range.setObjectName("range")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.range)
        self.label_16 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(80, 27))
        self.label_16.setMaximumSize(QtCore.QSize(80, 27))
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.sb_period = QtWidgets.QDoubleSpinBox(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_period.sizePolicy().hasHeightForWidth())
        self.sb_period.setSizePolicy(sizePolicy)
        self.sb_period.setMinimumSize(QtCore.QSize(100, 27))
        self.sb_period.setMaximumSize(QtCore.QSize(100, 27))
        self.sb_period.setDecimals(3)
        self.sb_period.setMinimum(0.001)
        self.sb_period.setMaximum(99.999)
        self.sb_period.setSingleStep(0.01)
        self.sb_period.setProperty("value", 1.0)
        self.sb_period.setObjectName("sb_period")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sb_period)
        self.Bplay = QtWidgets.QPushButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bplay.sizePolicy().hasHeightForWidth())
        self.Bplay.setSizePolicy(sizePolicy)
        self.Bplay.setMinimumSize(QtCore.QSize(100, 27))
        self.Bplay.setMaximumSize(QtCore.QSize(100, 27))
        self.Bplay.setCheckable(True)
        self.Bplay.setObjectName("Bplay")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Bplay)
        self.Bstop = QtWidgets.QPushButton(self.tab1)
        self.Bstop.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop.sizePolicy().hasHeightForWidth())
        self.Bstop.setSizePolicy(sizePolicy)
        self.Bstop.setMinimumSize(QtCore.QSize(100, 27))
        self.Bstop.setMaximumSize(QtCore.QSize(100, 27))
        self.Bstop.setObjectName("Bstop")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Bstop)
        self.label_18 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(110, 27))
        self.label_18.setMaximumSize(QtCore.QSize(110, 27))
        self.label_18.setObjectName("label_18")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.last_value = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last_value.sizePolicy().hasHeightForWidth())
        self.last_value.setSizePolicy(sizePolicy)
        self.last_value.setMinimumSize(QtCore.QSize(100, 27))
        self.last_value.setMaximumSize(QtCore.QSize(100, 27))
        self.last_value.setAlignment(QtCore.Qt.AlignCenter)
        self.last_value.setObjectName("last_value")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.last_value)
        self.label_19 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(110, 27))
        self.label_19.setMaximumSize(QtCore.QSize(110, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.tab1)
        self.label_20.setMinimumSize(QtCore.QSize(110, 27))
        self.label_20.setMaximumSize(QtCore.QSize(110, 27))
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.dac_value = QtWidgets.QDoubleSpinBox(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dac_value.sizePolicy().hasHeightForWidth())
        self.dac_value.setSizePolicy(sizePolicy)
        self.dac_value.setMinimumSize(QtCore.QSize(100, 27))
        self.dac_value.setMaximumSize(QtCore.QSize(100, 27))
        self.dac_value.setDecimals(3)
        self.dac_value.setSingleStep(0.1)
        self.dac_value.setObjectName("dac_value")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.dac_value)
        self.Bset_voltage = QtWidgets.QPushButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bset_voltage.sizePolicy().hasHeightForWidth())
        self.Bset_voltage.setSizePolicy(sizePolicy)
        self.Bset_voltage.setMinimumSize(QtCore.QSize(100, 27))
        self.Bset_voltage.setMaximumSize(QtCore.QSize(100, 27))
        self.Bset_voltage.setObjectName("Bset_voltage")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.Bset_voltage)
        self.horizontalLayout_6.addLayout(self.formLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotWidget = MPL_Widget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(560, 400))
        self.plotWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotWidget.setObjectName("plotWidget")
        self.verticalLayout_2.addWidget(self.plotWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cBosc = QtWidgets.QCheckBox(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBosc.sizePolicy().hasHeightForWidth())
        self.cBosc.setSizePolicy(sizePolicy)
        self.cBosc.setMinimumSize(QtCore.QSize(165, 22))
        self.cBosc.setMaximumSize(QtCore.QSize(165, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cBosc.setFont(font)
        self.cBosc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cBosc.setAutoFillBackground(False)
        self.cBosc.setObjectName("cBosc")
        self.horizontalLayout.addWidget(self.cBosc)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(15, 10, 171, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, 271, 452))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.cbD1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbD1.sizePolicy().hasHeightForWidth())
        self.cbD1.setSizePolicy(sizePolicy)
        self.cbD1.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD1.setObjectName("cbD1")
        self.cbD1.addItem("")
        self.cbD1.addItem("")
        self.gridLayout.addWidget(self.cbD1, 0, 1, 1, 1)
        self.cbD5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbD5.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD5.setObjectName("cbD5")
        self.cbD5.addItem("")
        self.cbD5.addItem("")
        self.gridLayout.addWidget(self.cbD5, 4, 1, 1, 1)
        self.cbD2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbD2.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD2.setObjectName("cbD2")
        self.cbD2.addItem("")
        self.cbD2.addItem("")
        self.gridLayout.addWidget(self.cbD2, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.cbD3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbD3.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD3.setObjectName("cbD3")
        self.cbD3.addItem("")
        self.cbD3.addItem("")
        self.gridLayout.addWidget(self.cbD3, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.Digital4 = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital4.sizePolicy().hasHeightForWidth())
        self.Digital4.setSizePolicy(sizePolicy)
        self.Digital4.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital4.setObjectName("Digital4")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.DDI4 = QtWidgets.QLCDNumber(self.page_11)
        self.DDI4.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI4.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.DDI4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DDI4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DDI4.setLineWidth(1)
        self.DDI4.setDigitCount(1)
        self.DDI4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.DDI4.setProperty("value", 1.0)
        self.DDI4.setObjectName("DDI4")
        self.Digital4.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.SDO4 = QtWidgets.QSlider(self.page_12)
        self.SDO4.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO4.setStyleSheet("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
"")
        self.SDO4.setMaximum(1)
        self.SDO4.setTracking(True)
        self.SDO4.setOrientation(QtCore.Qt.Horizontal)
        self.SDO4.setInvertedAppearance(False)
        self.SDO4.setInvertedControls(False)
        self.SDO4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SDO4.setTickInterval(1)
        self.SDO4.setObjectName("SDO4")
        self.label_28 = QtWidgets.QLabel(self.page_12)
        self.label_28.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.Digital4.addWidget(self.page_12)
        self.gridLayout.addWidget(self.Digital4, 3, 2, 1, 1)
        self.cbD4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbD4.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD4.setObjectName("cbD4")
        self.cbD4.addItem("")
        self.cbD4.addItem("")
        self.gridLayout.addWidget(self.cbD4, 3, 1, 1, 1)
        self.Digital5 = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital5.sizePolicy().hasHeightForWidth())
        self.Digital5.setSizePolicy(sizePolicy)
        self.Digital5.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital5.setObjectName("Digital5")
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.DDI5 = QtWidgets.QLCDNumber(self.page_13)
        self.DDI5.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI5.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.DDI5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DDI5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DDI5.setLineWidth(1)
        self.DDI5.setDigitCount(1)
        self.DDI5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.DDI5.setProperty("value", 1.0)
        self.DDI5.setObjectName("DDI5")
        self.Digital5.addWidget(self.page_13)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.SDO5 = QtWidgets.QSlider(self.page_14)
        self.SDO5.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO5.setStyleSheet("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
"")
        self.SDO5.setMaximum(1)
        self.SDO5.setTracking(True)
        self.SDO5.setOrientation(QtCore.Qt.Horizontal)
        self.SDO5.setInvertedAppearance(False)
        self.SDO5.setInvertedControls(False)
        self.SDO5.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SDO5.setTickInterval(1)
        self.SDO5.setObjectName("SDO5")
        self.label_29 = QtWidgets.QLabel(self.page_14)
        self.label_29.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.Digital5.addWidget(self.page_14)
        self.gridLayout.addWidget(self.Digital5, 4, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 0, 1, 1)
        self.cbD6 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbD6.setMinimumSize(QtCore.QSize(100, 27))
        self.cbD6.setObjectName("cbD6")
        self.cbD6.addItem("")
        self.cbD6.addItem("")
        self.gridLayout.addWidget(self.cbD6, 5, 1, 1, 1)
        self.Digital2 = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital2.sizePolicy().hasHeightForWidth())
        self.Digital2.setSizePolicy(sizePolicy)
        self.Digital2.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital2.setObjectName("Digital2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.DDI2 = QtWidgets.QLCDNumber(self.page_7)
        self.DDI2.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI2.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.DDI2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DDI2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DDI2.setLineWidth(1)
        self.DDI2.setDigitCount(1)
        self.DDI2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.DDI2.setProperty("value", 1.0)
        self.DDI2.setObjectName("DDI2")
        self.Digital2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.SDO2 = QtWidgets.QSlider(self.page_8)
        self.SDO2.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO2.setStyleSheet("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
"")
        self.SDO2.setMaximum(1)
        self.SDO2.setTracking(True)
        self.SDO2.setOrientation(QtCore.Qt.Horizontal)
        self.SDO2.setInvertedAppearance(False)
        self.SDO2.setInvertedControls(False)
        self.SDO2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SDO2.setTickInterval(1)
        self.SDO2.setObjectName("SDO2")
        self.label_21 = QtWidgets.QLabel(self.page_8)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.Digital2.addWidget(self.page_8)
        self.gridLayout.addWidget(self.Digital2, 1, 2, 1, 1)
        self.Digital3 = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital3.sizePolicy().hasHeightForWidth())
        self.Digital3.setSizePolicy(sizePolicy)
        self.Digital3.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital3.setObjectName("Digital3")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.DDI3 = QtWidgets.QLCDNumber(self.page_9)
        self.DDI3.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI3.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.DDI3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DDI3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DDI3.setLineWidth(1)
        self.DDI3.setDigitCount(1)
        self.DDI3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.DDI3.setProperty("value", 1.0)
        self.DDI3.setObjectName("DDI3")
        self.Digital3.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.SDO3 = QtWidgets.QSlider(self.page_10)
        self.SDO3.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO3.setStyleSheet("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
"")
        self.SDO3.setMaximum(1)
        self.SDO3.setTracking(True)
        self.SDO3.setOrientation(QtCore.Qt.Horizontal)
        self.SDO3.setInvertedAppearance(False)
        self.SDO3.setInvertedControls(False)
        self.SDO3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SDO3.setTickInterval(1)
        self.SDO3.setObjectName("SDO3")
        self.label_22 = QtWidgets.QLabel(self.page_10)
        self.label_22.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.Digital3.addWidget(self.page_10)
        self.gridLayout.addWidget(self.Digital3, 2, 2, 1, 1)
        self.Digital6 = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital6.sizePolicy().hasHeightForWidth())
        self.Digital6.setSizePolicy(sizePolicy)
        self.Digital6.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital6.setObjectName("Digital6")
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.DDI6 = QtWidgets.QLCDNumber(self.page_15)
        self.DDI6.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI6.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.DDI6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DDI6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DDI6.setLineWidth(1)
        self.DDI6.setDigitCount(1)
        self.DDI6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.DDI6.setProperty("value", 1.0)
        self.DDI6.setObjectName("DDI6")
        self.Digital6.addWidget(self.page_15)
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.SDO6 = QtWidgets.QSlider(self.page_16)
        self.SDO6.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO6.setStyleSheet("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
"")
        self.SDO6.setMaximum(1)
        self.SDO6.setTracking(True)
        self.SDO6.setOrientation(QtCore.Qt.Horizontal)
        self.SDO6.setInvertedAppearance(False)
        self.SDO6.setInvertedControls(False)
        self.SDO6.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SDO6.setTickInterval(1)
        self.SDO6.setObjectName("SDO6")
        self.label_30 = QtWidgets.QLabel(self.page_16)
        self.label_30.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.Digital6.addWidget(self.page_16)
        self.gridLayout.addWidget(self.Digital6, 5, 2, 1, 1)
        self.Digital1 = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Digital1.sizePolicy().hasHeightForWidth())
        self.Digital1.setSizePolicy(sizePolicy)
        self.Digital1.setMinimumSize(QtCore.QSize(70, 70))
        self.Digital1.setObjectName("Digital1")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.DDI1 = QtWidgets.QLCDNumber(self.page_5)
        self.DDI1.setGeometry(QtCore.QRect(10, 15, 40, 40))
        self.DDI1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DDI1.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.DDI1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DDI1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DDI1.setLineWidth(1)
        self.DDI1.setDigitCount(1)
        self.DDI1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.DDI1.setProperty("value", 1.0)
        self.DDI1.setObjectName("DDI1")
        self.Digital1.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_17 = QtWidgets.QLabel(self.page_6)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.SDO1 = QtWidgets.QSlider(self.page_6)
        self.SDO1.setGeometry(QtCore.QRect(0, 20, 65, 29))
        self.SDO1.setStyleSheet("alternate-background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 170, 0);\n"
"")
        self.SDO1.setMaximum(1)
        self.SDO1.setTracking(True)
        self.SDO1.setOrientation(QtCore.Qt.Horizontal)
        self.SDO1.setInvertedAppearance(False)
        self.SDO1.setInvertedControls(False)
        self.SDO1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SDO1.setTickInterval(1)
        self.SDO1.setObjectName("SDO1")
        self.Digital1.addWidget(self.page_6)
        self.gridLayout.addWidget(self.Digital1, 0, 2, 1, 1)
        self.Bupdate = QtWidgets.QPushButton(self.tab_2)
        self.Bupdate.setGeometry(QtCore.QRect(250, 500, 99, 27))
        self.Bupdate.setObjectName("Bupdate")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 533, 299))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cb = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb.sizePolicy().hasHeightForWidth())
        self.cb.setSizePolicy(sizePolicy)
        self.cb.setMinimumSize(QtCore.QSize(120, 27))
        self.cb.setObjectName("cb")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb)
        self.verticalLayout_4.addLayout(self.formLayout_6)
        self.sW = QtWidgets.QStackedWidget(self.layoutWidget)
        self.sW.setMinimumSize(QtCore.QSize(280, 200))
        self.sW.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sW.setAutoFillBackground(False)
        self.sW.setObjectName("sW")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_35 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setMinimumSize(QtCore.QSize(511, 40))
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_35.setLineWidth(0)
        self.label_35.setTextFormat(QtCore.Qt.RichText)
        self.label_35.setScaledContents(False)
        self.label_35.setWordWrap(False)
        self.label_35.setIndent(-1)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_7.addWidget(self.label_35)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_25 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_3 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.Bstart_encoder = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstart_encoder.sizePolicy().hasHeightForWidth())
        self.Bstart_encoder.setSizePolicy(sizePolicy)
        self.Bstart_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstart_encoder.setStyleSheet("")
        self.Bstart_encoder.setCheckable(True)
        self.Bstart_encoder.setObjectName("Bstart_encoder")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Bstart_encoder)
        self.Bstop_encoder = QtWidgets.QPushButton(self.page)
        self.Bstop_encoder.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop_encoder.sizePolicy().hasHeightForWidth())
        self.Bstop_encoder.setSizePolicy(sizePolicy)
        self.Bstop_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstop_encoder.setCheckable(True)
        self.Bstop_encoder.setChecked(True)
        self.Bstop_encoder.setObjectName("Bstop_encoder")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Bstop_encoder)
        self.mode_encoder = QtWidgets.QComboBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_encoder.sizePolicy().hasHeightForWidth())
        self.mode_encoder.setSizePolicy(sizePolicy)
        self.mode_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.mode_encoder.setObjectName("mode_encoder")
        self.mode_encoder.addItem("")
        self.mode_encoder.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mode_encoder)
        self.result_encoder = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_encoder.sizePolicy().hasHeightForWidth())
        self.result_encoder.setSizePolicy(sizePolicy)
        self.result_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.result_encoder.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.result_encoder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_encoder.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.result_encoder.setText("")
        self.result_encoder.setObjectName("result_encoder")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.result_encoder)
        self.resolution_encoder = QtWidgets.QSpinBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolution_encoder.sizePolicy().hasHeightForWidth())
        self.resolution_encoder.setSizePolicy(sizePolicy)
        self.resolution_encoder.setMinimumSize(QtCore.QSize(120, 27))
        self.resolution_encoder.setMaximum(65535)
        self.resolution_encoder.setSingleStep(1)
        self.resolution_encoder.setObjectName("resolution_encoder")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.resolution_encoder)
        self.verticalLayout_7.addLayout(self.formLayout_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.sW.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_32 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(511, 40))
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_32.setLineWidth(0)
        self.label_32.setTextFormat(QtCore.Qt.RichText)
        self.label_32.setScaledContents(False)
        self.label_32.setWordWrap(False)
        self.label_32.setIndent(-1)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_26 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lEPeriod = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lEPeriod.sizePolicy().hasHeightForWidth())
        self.lEPeriod.setSizePolicy(sizePolicy)
        self.lEPeriod.setMinimumSize(QtCore.QSize(120, 27))
        self.lEPeriod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lEPeriod.setText("")
        self.lEPeriod.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lEPeriod.setObjectName("lEPeriod")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lEPeriod)
        self.label_31 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cbTime = QtWidgets.QComboBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTime.sizePolicy().hasHeightForWidth())
        self.cbTime.setSizePolicy(sizePolicy)
        self.cbTime.setMinimumSize(QtCore.QSize(120, 27))
        self.cbTime.setObjectName("cbTime")
        self.cbTime.addItem("")
        self.cbTime.addItem("")
        self.cbTime.addItem("")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbTime)
        self.Bstart_capture = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstart_capture.sizePolicy().hasHeightForWidth())
        self.Bstart_capture.setSizePolicy(sizePolicy)
        self.Bstart_capture.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstart_capture.setCheckable(True)
        self.Bstart_capture.setAutoRepeat(False)
        self.Bstart_capture.setAutoExclusive(False)
        self.Bstart_capture.setAutoDefault(False)
        self.Bstart_capture.setObjectName("Bstart_capture")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Bstart_capture)
        self.Bstop_capture = QtWidgets.QPushButton(self.page_2)
        self.Bstop_capture.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop_capture.sizePolicy().hasHeightForWidth())
        self.Bstop_capture.setSizePolicy(sizePolicy)
        self.Bstop_capture.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstop_capture.setCheckable(False)
        self.Bstop_capture.setObjectName("Bstop_capture")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Bstop_capture)
        self.label_36 = QtWidgets.QLabel(self.page_2)
        self.label_36.setObjectName("label_36")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.lEHz = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lEHz.sizePolicy().hasHeightForWidth())
        self.lEHz.setSizePolicy(sizePolicy)
        self.lEHz.setMinimumSize(QtCore.QSize(120, 27))
        self.lEHz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lEHz.setText("")
        self.lEHz.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lEHz.setObjectName("lEHz")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lEHz)
        self.reference_period = QtWidgets.QDoubleSpinBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reference_period.sizePolicy().hasHeightForWidth())
        self.reference_period.setSizePolicy(sizePolicy)
        self.reference_period.setMinimumSize(QtCore.QSize(120, 27))
        self.reference_period.setDecimals(3)
        self.reference_period.setMaximum(9999.0)
        self.reference_period.setProperty("value", 2.0)
        self.reference_period.setObjectName("reference_period")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.reference_period)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.sW.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_33 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMinimumSize(QtCore.QSize(511, 40))
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_33.setLineWidth(0)
        self.label_33.setTextFormat(QtCore.Qt.RichText)
        self.label_33.setScaledContents(False)
        self.label_33.setWordWrap(False)
        self.label_33.setIndent(-1)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_5.addWidget(self.label_33)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_27 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.Bstart_counter = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstart_counter.sizePolicy().hasHeightForWidth())
        self.Bstart_counter.setSizePolicy(sizePolicy)
        self.Bstart_counter.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstart_counter.setCheckable(True)
        self.Bstart_counter.setObjectName("Bstart_counter")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Bstart_counter)
        self.Bstop_counter = QtWidgets.QPushButton(self.page_3)
        self.Bstop_counter.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop_counter.sizePolicy().hasHeightForWidth())
        self.Bstop_counter.setSizePolicy(sizePolicy)
        self.Bstop_counter.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstop_counter.setCheckable(True)
        self.Bstop_counter.setChecked(True)
        self.Bstop_counter.setObjectName("Bstop_counter")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Bstop_counter)
        self.counter_result = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counter_result.sizePolicy().hasHeightForWidth())
        self.counter_result.setSizePolicy(sizePolicy)
        self.counter_result.setMinimumSize(QtCore.QSize(120, 27))
        self.counter_result.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.counter_result.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.counter_result.setText("")
        self.counter_result.setObjectName("counter_result")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.counter_result)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.sW.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_34 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setMinimumSize(QtCore.QSize(511, 40))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_34.setLineWidth(0)
        self.label_34.setTextFormat(QtCore.Qt.RichText)
        self.label_34.setScaledContents(False)
        self.label_34.setWordWrap(False)
        self.label_34.setIndent(-1)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_6.addWidget(self.label_34)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 27))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.periodPWM = QtWidgets.QSpinBox(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodPWM.sizePolicy().hasHeightForWidth())
        self.periodPWM.setSizePolicy(sizePolicy)
        self.periodPWM.setMinimumSize(QtCore.QSize(120, 27))
        self.periodPWM.setMaximum(65535)
        self.periodPWM.setObjectName("periodPWM")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.periodPWM)
        self.label_6 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.dutyPWM = QtWidgets.QSpinBox(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dutyPWM.sizePolicy().hasHeightForWidth())
        self.dutyPWM.setSizePolicy(sizePolicy)
        self.dutyPWM.setMinimumSize(QtCore.QSize(120, 27))
        self.dutyPWM.setMaximum(100)
        self.dutyPWM.setProperty("value", 50)
        self.dutyPWM.setObjectName("dutyPWM")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dutyPWM)
        self.Bset_pwm = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bset_pwm.sizePolicy().hasHeightForWidth())
        self.Bset_pwm.setSizePolicy(sizePolicy)
        self.Bset_pwm.setMinimumSize(QtCore.QSize(120, 27))
        self.Bset_pwm.setCheckable(True)
        self.Bset_pwm.setObjectName("Bset_pwm")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Bset_pwm)
        self.Bstop_pwm = QtWidgets.QPushButton(self.page_4)
        self.Bstop_pwm.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop_pwm.sizePolicy().hasHeightForWidth())
        self.Bstop_pwm.setSizePolicy(sizePolicy)
        self.Bstop_pwm.setMinimumSize(QtCore.QSize(120, 27))
        self.Bstop_pwm.setObjectName("Bstop_pwm")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Bstop_pwm)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.sW.addWidget(self.page_4)
        self.verticalLayout_4.addWidget(self.sW)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 27))
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConfig = QtWidgets.QAction(mainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfig.setIcon(icon)
        self.actionConfig.setIconVisibleInMenu(True)
        self.actionConfig.setObjectName("actionConfig")
        self.actionCSV = QtWidgets.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/CSV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCSV.setIcon(icon1)
        self.actionCSV.setObjectName("actionCSV")
        self.toolBar.addAction(self.actionConfig)
        self.toolBar.addAction(self.actionCSV)
        self.toolBar.addSeparator()

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Digital4.setCurrentIndex(0)
        self.Digital5.setCurrentIndex(0)
        self.Digital2.setCurrentIndex(0)
        self.Digital3.setCurrentIndex(0)
        self.Digital6.setCurrentIndex(0)
        self.Digital1.setCurrentIndex(0)
        self.sW.setCurrentIndex(0)
        self.Bstart_capture.clicked['bool'].connect(self.Bstop_capture.setEnabled)
        self.Bstop_capture.clicked['bool'].connect(self.Bstop_capture.setEnabled)
        self.Bstop_capture.clicked['bool'].connect(self.Bstart_capture.toggle)
        self.Bstart_counter.toggled['bool'].connect(self.Bstop_counter.setEnabled)
        self.Bset_pwm.clicked['bool'].connect(self.Bstop_pwm.setEnabled)
        self.Bstop_pwm.clicked['bool'].connect(self.Bset_pwm.setChecked)
        self.Bstop_pwm.clicked['bool'].connect(self.Bstop_pwm.setEnabled)
        self.Bset_pwm.toggled['bool'].connect(self.Bset_pwm.setDisabled)
        self.cbD2.currentIndexChanged['int'].connect(self.Digital2.setCurrentIndex)
        self.cbD3.currentIndexChanged['int'].connect(self.Digital3.setCurrentIndex)
        self.cbD4.currentIndexChanged['int'].connect(self.Digital4.setCurrentIndex)
        self.cbD5.currentIndexChanged['int'].connect(self.Digital5.setCurrentIndex)
        self.cbD6.currentIndexChanged['int'].connect(self.Digital6.setCurrentIndex)
        self.cb.currentIndexChanged['int'].connect(self.sW.setCurrentIndex)
        self.Bstop.clicked['bool'].connect(self.Bplay.toggle)
        self.Bplay.clicked['bool'].connect(self.Bstop.setEnabled)
        self.Bstop.clicked['bool'].connect(self.Bstop.setEnabled)
        self.SDO1.valueChanged['int'].connect(self.label_17.setNum)
        self.cbD1.currentIndexChanged['int'].connect(self.Digital1.setCurrentIndex)
        self.SDO2.valueChanged['int'].connect(self.label_21.setNum)
        self.SDO3.valueChanged['int'].connect(self.label_22.setNum)
        self.SDO4.valueChanged['int'].connect(self.label_28.setNum)
        self.SDO5.valueChanged['int'].connect(self.label_29.setNum)
        self.SDO6.valueChanged['int'].connect(self.label_30.setNum)
        self.Bplay.toggled['bool'].connect(self.pos_channel.setDisabled)
        self.Bplay.toggled['bool'].connect(self.neg_channel.setDisabled)
        self.Bplay.toggled['bool'].connect(self.range.setDisabled)
        self.Bplay.toggled['bool'].connect(self.sb_period.setDisabled)
        self.Bstop_counter.clicked['bool'].connect(self.Bstart_counter.toggle)
        self.Bstart_counter.clicked['bool'].connect(self.Bstop_counter.toggle)
        self.Bstart_encoder.toggled['bool'].connect(self.Bstop_encoder.setEnabled)
        self.Bstop_encoder.clicked['bool'].connect(self.Bstart_encoder.toggle)
        self.Bstart_encoder.clicked['bool'].connect(self.Bstop_encoder.toggle)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "DAQControl"))
        self.label_12.setText(_translate("mainWindow", "Analog Input"))
        self.label_13.setText(_translate("mainWindow", "Ch +"))
        self.label_14.setText(_translate("mainWindow", "Ch -"))
        self.label_15.setText(_translate("mainWindow", "Range"))
        self.label_16.setText(_translate("mainWindow", "Period (s)"))
        self.Bplay.setText(_translate("mainWindow", "Play"))
        self.Bstop.setText(_translate("mainWindow", "Stop"))
        self.label_18.setText(_translate("mainWindow", "Last Value (V)"))
        self.last_value.setText(_translate("mainWindow", "-"))
        self.label_19.setText(_translate("mainWindow", "Analog Output"))
        self.label_20.setText(_translate("mainWindow", "DAC Value (V)"))
        self.Bset_voltage.setText(_translate("mainWindow", "Set Voltage"))
        self.cBosc.setText(_translate("mainWindow", "Oscilloscope mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("mainWindow", "Analog I / O"))
        self.label_7.setText(_translate("mainWindow", "Select Input or Output"))
        self.label_8.setText(_translate("mainWindow", "D1"))
        self.label_23.setText(_translate("mainWindow", "D5"))
        self.label_9.setText(_translate("mainWindow", "D2"))
        self.cbD1.setItemText(0, _translate("mainWindow", "Input"))
        self.cbD1.setItemText(1, _translate("mainWindow", "Output"))
        self.cbD5.setItemText(0, _translate("mainWindow", "Input"))
        self.cbD5.setItemText(1, _translate("mainWindow", "Output"))
        self.cbD2.setItemText(0, _translate("mainWindow", "Input"))
        self.cbD2.setItemText(1, _translate("mainWindow", "Output"))
        self.label_10.setText(_translate("mainWindow", "D3"))
        self.cbD3.setItemText(0, _translate("mainWindow", "Input"))
        self.cbD3.setItemText(1, _translate("mainWindow", "Output"))
        self.label_11.setText(_translate("mainWindow", "D4"))
        self.label_28.setText(_translate("mainWindow", "0"))
        self.cbD4.setItemText(0, _translate("mainWindow", "Input"))
        self.cbD4.setItemText(1, _translate("mainWindow", "Output"))
        self.label_29.setText(_translate("mainWindow", "0"))
        self.label_24.setText(_translate("mainWindow", "D6"))
        self.cbD6.setItemText(0, _translate("mainWindow", "Input"))
        self.cbD6.setItemText(1, _translate("mainWindow", "Output"))
        self.label_21.setText(_translate("mainWindow", "0"))
        self.label_22.setText(_translate("mainWindow", "0"))
        self.label_30.setText(_translate("mainWindow", "0"))
        self.label_17.setText(_translate("mainWindow", "0"))
        self.Bupdate.setText(_translate("mainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Digital I / O"))
        self.label.setText(_translate("mainWindow", "Select Mode:"))
        self.cb.setItemText(0, _translate("mainWindow", "Encoder"))
        self.cb.setItemText(1, _translate("mainWindow", "Capture"))
        self.cb.setItemText(2, _translate("mainWindow", "Counter"))
        self.cb.setItemText(3, _translate("mainWindow", "PWM"))
        self.label_35.setText(_translate("mainWindow", "<html><head/><body><p>Reads encoder input signals. Internally connected to D5 and D6.<br/>- D6: keeps track of the number of pulses given by the encoder (position).<br/>- D5: is used to check the displacement between signals (direction). </p></body></html>"))
        self.label_25.setText(_translate("mainWindow", "Result:"))
        self.label_3.setText(_translate("mainWindow", "Select Mode:"))
        self.label_4.setText(_translate("mainWindow", "Resolution :"))
        self.Bstart_encoder.setText(_translate("mainWindow", "Start Encoder"))
        self.Bstop_encoder.setText(_translate("mainWindow", "Stop Encoder"))
        self.mode_encoder.setItemText(0, _translate("mainWindow", "Circular"))
        self.mode_encoder.setItemText(1, _translate("mainWindow", "Lineal"))
        self.label_32.setText(_translate("mainWindow", "<html><head/><body><p>Permits measuring the time length of incoming digital signals.<br/>- Internally connected to D5. </p></body></html>"))
        self.label_26.setText(_translate("mainWindow", "Result (ms): "))
        self.label_31.setText(_translate("mainWindow", "Reference (ms): "))
        self.label_2.setText(_translate("mainWindow", "Select width : "))
        self.cbTime.setItemText(0, _translate("mainWindow", "Low time"))
        self.cbTime.setItemText(1, _translate("mainWindow", "High time"))
        self.cbTime.setItemText(2, _translate("mainWindow", "Full period"))
        self.Bstart_capture.setText(_translate("mainWindow", "Start Capture"))
        self.Bstop_capture.setText(_translate("mainWindow", "Stop Capture"))
        self.label_36.setText(_translate("mainWindow", "Result (Hz): "))
        self.label_33.setText(_translate("mainWindow", "<html><head/><body><p>Counts and stores the number of state changes in a external digital signal.<br/>- Internally connected to D5. </p></body></html>"))
        self.label_27.setText(_translate("mainWindow", "Result:"))
        self.Bstart_counter.setText(_translate("mainWindow", "Start Counter"))
        self.Bstop_counter.setText(_translate("mainWindow", "Stop Counter"))
        self.label_34.setText(_translate("mainWindow", "<html><head/><body><p>Generates a continuous digital signal at a given frequency.<br/>- Duty refers to the portion of time that the signal spends in High state.<br/>- Internally connected to D5. </p></body></html>"))
        self.label_5.setText(_translate("mainWindow", "Period (µs) :"))
        self.label_6.setText(_translate("mainWindow", "Duty (%) :"))
        self.Bset_pwm.setText(_translate("mainWindow", "Set PWM"))
        self.Bstop_pwm.setText(_translate("mainWindow", "Stop PWM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Timer-Counter"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionConfig.setText(_translate("mainWindow", "config"))
        self.actionCSV.setText(_translate("mainWindow", "CSV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

